# -*- coding: utf-8 -*-
"""student_roadmaps.json.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QaJH1o1JlGqg9BCHTWMnZZQQTOSynB0d
"""

import json
from datetime import datetime

# -----------------------------
# Student Profile Class
# -----------------------------
class StudentProfile:
    def __init__(self, usn, name, phone):
        self.usn = usn
        self.name = name
        self.phone = phone

    def to_dict(self):
        return {
            "usn": self.usn,
            "name": self.name,
            "phone": self.phone
        }


# -----------------------------
# Roadmap Generator Class
# -----------------------------
class RoadmapGenerator:

    def __init__(self):
        self.roadmaps = {}

    def generate_roadmap(self, skill, level):
        skill = skill.lower()
        level = level.lower()

        roadmap = {
            "skill": skill,
            "level": level,
            "created_at": str(datetime.now()),
            "steps": []
        }

        if skill == "python":
            if level == "beginner":
                roadmap["steps"] = [
                    "Learn Python Basics",
                    "Practice Data Types",
                    "Control Flow",
                    "Functions",
                    "Mini Project"
                ]
            elif level == "intermediate":
                roadmap["steps"] = [
                    "OOP Concepts",
                    "File Handling",
                    "Exception Handling",
                    "Libraries (NumPy, Pandas)",
                    "Build Real Project"
                ]
            else:
                roadmap["steps"] = [
                    "Decorators",
                    "Generators",
                    "API Development",
                    "Testing & Logging",
                    "Advanced Project"
                ]

        elif skill == "ai":
            roadmap["steps"] = [
                "Python for AI",
                "NumPy & Pandas",
                "Data Visualization",
                "Machine Learning Basics",
                "Build ML Project"
            ]

        elif skill == "cybersecurity":
            roadmap["steps"] = [
                "Networking Basics",
                "Linux Fundamentals",
                "Cryptography Basics",
                "Python for Security",
                "Build Security Tool"
            ]

        else:
            roadmap["steps"] = [
                "Research Fundamentals",
                "Build Foundation",
                "Practice Daily",
                "Create Projects",
                "Join Community"
            ]

        return roadmap


# -----------------------------
# Data Storage Manager
# -----------------------------
class DataManager:

    FILE_NAME = "student_roadmaps.json"

    @staticmethod
    def save_data(data):
        with open(DataManager.FILE_NAME, "w") as file:
            json.dump(data, file, indent=4)

    @staticmethod
    def load_data():
        try:
            with open(DataManager.FILE_NAME, "r") as file:
                return json.load(file)
        except FileNotFoundError:
            return {}


# -----------------------------
# Main Program
# -----------------------------
def main():
    print("===== AI-Based Roadmap Generator =====")

    # Load existing data
    database = DataManager.load_data()

    usn = input("Enter USN: ")
    name = input("Enter Name: ")
    phone = input("Enter Phone Number: ")

    student = StudentProfile(usn, name, phone)

    skill = input("Enter Skill (Python / AI / Cybersecurity): ")
    level = input("Enter Level (Beginner / Intermediate / Advanced): ")

    generator = RoadmapGenerator()
    roadmap = generator.generate_roadmap(skill, level)

    # Store in database
    database[usn] = {
        "profile": student.to_dict(),
        "roadmap": roadmap
    }

    DataManager.save_data(database)

    print("\n✅ Roadmap Generated Successfully!\n")
    print(json.dumps(database[usn], indent=4))


# Run the program
if __name__ == "__main__":
    main()

